### ISSUE TITLE
As an OmbuLabs / FastRuby.io developer, I'd like to be able to pick which style guide to use in my new Rails application 

### ISSUE THREAD

**Issue by etagwerker** [fastruby/rails-template#1]
### Why

**As a developer**
**I want to be able to pick the style guide**
**So that I can save time implementing it in my project**

### Acceptance Criteria

```gherkin
Scenario: 
Given that we have three style guides (no style guide (Rails's default), OmbuLabs, or FastRuby.io)
When I start creating a new Rails project
Then I want to be able to pick the style guide for my project
```

**Notes:**

It would be great if there is a little dialogue that is presented to the user or an option to pick the style guide. 

For example: 

```
rails new foo
> Which style guide do you want to use? (rails/fastruby/ombulabs -- default: ombulabs)
> fastruby
> Cool, using fastruby style guide for project foo.
```

Or: 

```
rails new foo --styleguide=fastruby
> Cool, using fastruby style guide for project foo.
```

**Comment by arielj** [comment]
@etagwerker I run into an issue here with the fastruby styleguide, it's not prepared to work with the Webpacker gem (webpacker can't read js files from gems like sprocket does for the old assets pipeline). We don't have that problem with the ombulabs one cause the js on that one is only used in the gh-page of the styleguide, but the fastruby one includes the js needed for the carousel and also js from bootstrap and material design.

We first need to make the fastruby styleguide compatible with webpacker (maybe trying to remove external dependencies like jquery, bootstrap, material and bs.slider to make it easier)

**Comment by arielj** [comment]
Looks like doing something like `rails new foo --styleguide=fastruby` is not possible with the standard rails command and rails templates (the AppGenerator filters unknown arguments). We would have to override the default AppGenerator class to add that and wrap that with a custom command like `suspenders` does, but then we would me moving out from the rails conventions.

**Comment by arielj** [comment]
This is partially implemented (asking the user to choose between ombulabs styleguide or none).
