### ISSUE TITLE
[BUG] Stop spring at the end of the process

### ISSUE THREAD

**Issue by neutrino** [fastruby/rails-template#16]
**IMPORTANT: please make sure you ask yourself all intro questions and fill all sections of the template.**

**Before we start...:**

- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository (for multi-repository projects)

**Version, Branch, or Commit:**
https://github.com/fastruby/rails-template/commit/25026e815ad1f8ee93a1c095a912a540296c3abb

**Expected behavior:**

It should terminate all the related processes.

**Actual behavior:**

We have lingering process from the newly generated Rails app.

**Steps to reproduce:**
1: Run `rails new test-app --rc=./rails-template/.railsrc -m ./rails-template/template.rb` from the parent directory of rails-template
2. `ps aux | grep ruby` lists few running processes 

**I will abide by the [code of conduct] (CODE_OF_CONDUCT.md)**

**Comment by arielj** [comment]
This was already fixed https://github.com/fastruby/rails-template/blob/main/template.rb#L269
